### ISSUE TITLE
entrypoint.sh does not wait for packaging to finish

### ISSUE THREAD

**Issue by StanleySweet** [0ad-matters/gh-action-build-pyromod#5]
On bigger mods packaging can take more than a few seconds. See https://github.com/0ADMods/xiiiad/actions/runs/3224966299/jobs/5276698900

Currently the script doesn't wait for it to finish, which can lead to a race condition

```sh
su user0ad --command "/home/user0ad/usr/bin/pyrogenesis  \
    -mod=package_mod   \
    -archivebuild=$INPUT_DIRECTORY  \
    -archivebuild-output=$OUTPUT_FILE    \
    -archivebuild-compress"

test -f "$OUTPUT_FILE"
zip -d "$OUTPUT_FILE" ".git*"
```

Should maybe be
```sh
su user0ad --command "/home/user0ad/usr/bin/pyrogenesis  \
    -mod=package_mod   \
    -archivebuild=$INPUT_DIRECTORY  \
    -archivebuild-output=$OUTPUT_FILE    \
    -archivebuild-compress" && \
    test -f "$OUTPUT_FILE"  && \
   zip -d "$OUTPUT_FILE" ".git*"

```
And find a way to wait for that.

**Comment by andy5995** [comment]
@StanleySweet Double ampersands after the pyrogenesis command wouldn't be robust (see https://trac.wildfiregames.com/ticket/6639), that's why I use the `test -f`.

And double ampersands generally aren't needed in this script because I have `set -e` at the top (The script will exit if any command fails, and return the error code of the command that failed).

I'll add a delay though. Do you think just adding `sync` would be adequate?

**Comment by StanleySweet** [comment]
Ah right that's not great indeed.  
The point of the ampersands was not to check for errors though. It was to wait for the packaging process to finish. For some mods it can take a while sometimes more than half an hour.
Not sure what sync would do
